### PR TITLE
adds OUR coin to coins file and updates nodes of RICK

### PR DESCRIPTION
**Pull request by gcharang**

### CODE REVIEW

**Comment by jl777** [comment]
I have been waiting for PR that adds support for various coins, but it is best to not create a duplicate entry. just add the new fields to the existing OUR item

**Comment by gcharang** [comment]
removed the extra entry and updated the existing one.

**Comment by jl777** [comment]
feel free to add the nSPV parameters for other coins

**Comment by gcharang** [comment]
will do!

**Pull request merged**
